version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:latest
    container_name: asa_pve_Server
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - MAP_NAME=TheIsland
      - SESSION_NAME=Server_name
      - SERVER_ADMIN_PASSWORD=MyPassword
      - ASA_PORT=7777
      - QUERY_PORT=27015
      - MAX_PLAYERS=70
      - CLUSTER_ID=cluster
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - "./ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "/home/factorioserver/ASA_Cluster/Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    memswap_limit: 16G
    mem_limit: 12G  
