version: '2.4'

services:
  darkandlight:
    build: .
    image: acekorneya/asa_server:latest
    container_name: test_asa_Server
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - MAP_NAME=TheIsland
      - SESSION_NAME=POK-test
      - SERVER_ADMIN_PASSWORD=Korneya512!
      - ASA_PORT=8781
      - QUERY_PORT=28018
      - MAX_PLAYERS=70
      - CLUSTER_ID=kny
    ports:
      - "8781:8781/tcp"
      - "8781:8781/udp"
      - "28018:28018/tcp"
      - "28018:28018/udp"
    volumes:
      - "./ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "./Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    cpuset: 8-11  # Pinning CPUs to threads 10-12
    memswap_limit: 16G
    mem_limit: 12G  # Setting memory limit to 12GB
